### ISSUE TITLE
Install via homebrew?

### ISSUE THREAD

**Issue by thedrow** [passy/givegif#1]
Can we install this via homebrew please? :)

**Comment by passy** [comment]
Yeah, I'd like to get this into some distributions! If someone wants to submit this, please go ahead. :)

**Comment by passy** [comment]
I'll add a custom tap, but I won't get it into core just yet:

```
1 file inspected, no offenses detected

==> audit problems
givegif:
 * GitHub repository not notable enough (<20 forks, <20 watchers and <50 stars)
 * GitHub repository too new (<30 days old)
```

**Comment by thedrow** [comment]
:+1: Thanks
